name: Deploy Hello World

on:
  push:
    branches:
      - main
      - dev
      - test
    paths:
      - 'hello-world/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set Environment
        run: |
          if [[ $GITHUB_REF_NAME == 'main' ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV=$GITHUB_REF_NAME" >> $GITHUB_ENV
          fi

      - name: Build and Deploy Hello World
        run: |
          cd hello-world
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ env.ENV }}-hello-world --resolve-s3 --capabilities CAPABILITY_IAM
