name: Deploy Hello World

on:
  push:
    branches:
      - main
      - dev
      - test
    paths:
      - 'hello-world/**'

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.env.outputs.env_name }}
    steps:
      - name: Set Environment Name
        id: env
        run: |
          if [[ $GITHUB_REF_NAME == 'main' ]]; then
            echo "env_name=prod" >> "$GITHUB_OUTPUT"
          else
            echo "env_name=$GITHUB_REF_NAME" >> "$GITHUB_OUTPUT"
          fi

  deploy-hello-world:
    needs: setup
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.env_name }}-hello-world
    steps:
      - uses: actions/checkout@v4
      
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::798920797034:role/GitHubDeployRole
          aws-region: us-east-1

      - name: Build and Deploy Hello World
        run: |
          cd hello-world
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ needs.setup.outputs.env_name }}-hello-world --resolve-s3 --capabilities CAPABILITY_IAM
